name: format
on:
  push:
    branches:
      - main
    paths:
      - '**.py'
jobs:
  postprocessing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Format with Ruff formatter
        uses: astral-sh/ruff-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: "format"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Format with Ruff"
